name: Upload Release Assets

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      run: make build
    - name: Rename file
      run: mv ./out/linux/0gchaind ./out/linux/0gchaind-linux-${{ github.ref_name }}
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ./out/linux/0gchaind-linux-${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.ZG_UPLOAD_ASSET }}
